# -*- coding: utf-8 -*-
"""Türkiye'de Yaşayan Suriyeli Mülteciler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z2yTipbPcWxRaqQ0NSRoCXeg5SYZef70

# Türkiyedeki Suriyeli Sayısı

Hedefimiz [multeciler.org](https://multeciler.org.tr/turkiyedeki-suriyeli-sayisi/) sayfasındaki raporu sayfa güncellendikçe otomatik oluşturmak.

## Verinin Yüklenmesi
"""

# Kütüphanelerimiz
import pandas as pd

# İlgili siteden verileri çekelim.
multeci = pd.read_html("https://multeciler.org.tr/turkiyedeki-suriyeli-sayisi/", header=0)

"""Yukarıda kullandığımız  `.read_html` metodu bize dataframelerden oluşan bir liste döndürür.

Listemizin kaç elemanı olduğuna `len()` fonksiyonu ile bakalım.
"""

print(len(multeci))

"""## Tablo 1

2 elemanlı bir liste olduğuna göre ilk dataframe'i **df**'ye eşitleyelim. 

Ardından ekrana bastıralım ve `.info()` ile dataframe özelliklerine bakalım.
"""

df = multeci[0]

print(df)

df.info()



"""### Verinin Temizlenmesi

Çektiğimiz değerler **string** ve içerisinde  **.** bulunuyor.

> Nüfus'a ait sayıları çekerken **.** bulunması python'un değerleri **float** olarak algılamasına ve *1 milyon olması gereken değerin 1 bin* olarak algılanmasına yol açacaktır.

Bütün bu karışıklıkları önlemek için **df** içerisindeki bütün **.**'ları kaldırıyoruz.

`apply()` fonksiyonu içerisinde bir **lambda** fonksiyonu işletiyoruz.

Buna göre her bir **x**'i önce **str** ifadeye ardından `.replace()` metodu ile içerisindeki **.**'ları boş bir değerle değiştiriyoruz.
"""

df = df.apply(lambda x: x.str.replace('.',''))

"""### Artık rapor içerisindeki Tablo-1 altındaki açıklamaları oluşturmaya çalışalım.

#### Ulaşmamız gereken yazı.

> Tabloya göre 0-18 yaş aralığında 1 milyon 662 bin 753 Suriyeli bulunuyor.
"""

# 0-18 dediği için .loc[1:4] aldık. Ve Kadın erkek toplam sütunu seçtik.
toplam_0_18 = df['TOPLAM'].loc[1:4].astype(int, errors='ignore').sum()

"""> Çektiğimiz değerin binler basamaklarına ayırmak için.

`.format()` metodunu kullandık. yazı içerisinde göstermek istediğimiz yere `{val:,}` koyduk ve format içerisinde `val=deger` yaptık.
"""

print("Tabloya göre 0-18 yaş aralığında {val:,} Suriyeli bulunuyor.".format(val=toplam_0_18))

"""#### Ulaşmamız gereken yazı.

> 10 yaşın altındaki Suriyeli sayısı ise bu ay 1 milyon 7 bin 453 kişi oldu.
"""

toplam_0_9 = df["TOPLAM"].loc[1:2].astype(int).sum()

print("10 yaşın altındaki Suriyeli sayısı ise bu ay {val:,} kişi oldu.".format(val=toplam_0_9))

"""#### Ulaşmamız gereken yazı.

> `Suriyelilerin %27,93’ü 10 yaşın altında.`
"""

yas_10_alti = df["TOPLAM"].loc[1:2].astype(int).sum()
yuzde_10 = yas_10_alti / (df["TOPLAM"].loc[1:15].astype(int).sum())

"""> **yuzde_10** değişkeni **0.27932532923803427** hem ondalık olarak hemde çok uzun bir şekilde gösteriliyor.



Bunun önüne geçebilmek için `.format()` metodumuzun yazı içerisindeki kısmına ` {:.2%}` ekliyoruz bu sayede ifademiz yüzdelik gösteriliyor.
"""

yuzde_10

print("Suriyelilerin {:.2%}’ü 10 yaşın altında.".format(yuzde_10))

# Görselleştirme
import matplotlib.pyplot as plt

slices_hours = [yas_10_alti,(df["TOPLAM"].loc[3:15].astype(int).sum()) ]
activities = ['10 Yaş Altı Kişi Sayısı', '10 ve Üzeri Kişi sayısı']
colors = ['y', 'r']
plt.pie(slices_hours, labels=activities, colors=colors, startangle=90, autopct='%.1f%%')
plt.show()

"""#### Ulaşmamız gereken yazı.

> Genç nüfus olarak tanımlanan 15-24 yaş aralığında  815 bin 128 kişi bulunuyor.
"""

toplam_15_24 =  df['TOPLAM'].loc[4:5].astype(int, errors='ignore').sum()

print("Genç nüfus olarak tanımlanan 15-24 yaş aralığında  {:,} kişi bulunuyor.".format(toplam_15_24))

"""#### Ulaşmamız gereken yazı.

> Suriyeli genç nüfusun toplam Suriyeli sayısındaki oranı %22,6. Türkiye’nin genç nüfus oranı ise %15,8.
"""

yuzde_genc = toplam_15_24 / (df["TOPLAM"].loc[1:15].astype(int).sum())

print("Suriyeli genç nüfusun toplam Suriyeli sayısındaki oranı {:.2%}. Türkiye’nin genç nüfus oranı ise %15,8.".format(yuzde_genc))

"""#### Ulaşmamız gereken yazı.

> Yaş tablosuna göre kayıtlı Suriyelilerin yaş ortalaması 22,5. Türkiye nüfusunun 2018 verilerine göre yaş ortalaması ise 31,7.
"""



"""#### Ulaşmamız gereken yazı.

> Suriyeli Erkeklerin Sayısı Suriyeli Kadınların Sayısından 299 bin 515 kişi daha fazla
"""

erkek_fark_kadin = (int(df.loc[0]["ERKEK"])) - (int(df.loc[0]["KADIN"]))

print("Suriyeli Erkeklerin Sayısı Suriyeli Kadınların Sayısından {:,} kişi daha fazla.".format(erkek_fark_kadin))

print(multeci[1])

